name:                today
version:             0.1.0.0
github:              "nobsun/today"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2021 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/today#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- bytestring
- utf8-string
- time
- arithmoi

library:
  source-dirs:          src

executables:
  today:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - today

tests:
  today-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - today
    - hspec
    - main-tester

  # today-doctest:
  #   main:                doctests.hs
  #   source-dirs:         test
  #   # ghc-options:
  #   # - -threaded
  #   # - -rtsopts
  #   # - -with-rtsopts=-N
  #   dependencies:
  #   - today
  #   - doctest
